---
title: "visualization"
author: "Huailin Tang"
date: "4/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("dplyr")
library("ggplot2")
library("sf")
library("maps")
library("tools")
library("rnaturalearth")
library("rnaturalearthdata")
theme_set(theme_bw())
sf_use_s2(FALSE) 
world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)
```

```{r}
transmission = read.csv("transmission_new.csv")
vaccination = read.csv("vaccination_new.csv")
Midwest = c("Kansas","Illinois", "Indiana", "Michigan", "Minnesota", "Missouri", "Nebraska", "North Dakota", "Ohio", "South Dakota", "Wisconsin", "Iowa")
```

# Midwest states map
```{r}
states <- st_as_sf(map("state", plot = FALSE, fill = TRUE))
head(states)
states <- cbind(states, st_coordinates(st_centroid(states)))
states$ID <- toTitleCase(states$ID)
head(states)
```

```{r}
ggplot(data = world) +
  geom_sf() +
  geom_sf(data = states, fill = NA) + 
  geom_label(data = states, 
             aes(X, Y, 
                 label = ifelse(ID %in% Midwest, paste0(ID), "")), 
             size = 4, fontface = "bold", 
             fill = alpha(c("gray"),0.1), label.size = 0, nudge_x = 0.1) +
  coord_sf(xlim = c(-105.5, -79), ylim = c(36.15, 49.5), expand = FALSE) +
  labs(x="Latitude", y="Longitude", title="Midwest states map") +
  theme(plot.title = element_text(hjust = 0.5))
```

# Midwest counties map
```{r}
counties <- st_as_sf(map("county", plot = FALSE, fill = TRUE))
counties <- subset(counties,
                   grepl(c("kansas|illinois|indiana|michigan|minnesota|missouri|nebraska|north dakota|ohio|south dakota|wisconsin|iowa"), counties$ID))
#remove Arkansas, Colorado, Kentucky, Pennsylvania from the map
counties <- subset(counties, !grepl(c("arkansas|colorado|kentucky|pennsylvania"), counties$ID)) 
counties$area <- as.numeric(st_area(counties))
head(counties)
```

```{r}
ggplot(data = world) +
  geom_sf() +
  geom_sf(data = states, lwd = 1)+
  geom_sf(data = counties, fill = NA, color = gray(.5)) +
  coord_sf(xlim = c(-105.5, -79), ylim = c(36.15, 49.5), expand = FALSE) +
  labs(x="Latitude", y="Longitude", title="Midwest counties map") +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
library("usdata")
library("lubridate")
library("tidyr")
transmssion<-readr::read_csv("transmission_new.csv")
vaccination<-readr::read_csv("vaccination_new.csv")
vac<-vaccination %>% 
  mutate(state = abbr2state(state)) %>% 
  rename(date=Date)
trans<-transmission %>% 
  rename(state=state_name, county=county_name) %>% 
  mutate(date = date(date))
vac_trans<-vac %>% 
  left_join(trans)

fill_data<-vac_trans %>% 
  group_by(county,state) %>% 
  summarise(percentPositive = mean(positive_pct)) %>% 
  mutate(ID = paste0(tolower(state),",",tolower(county))) %>% 
  ungroup() %>% 
  separate(ID, c("ID","county"), sep = " ") %>% 
  transmute(percentPositive,ID)
fill_<-counties %>% 
  left_join(fill_data)
whole_map<-ggplot(data = world) +
  geom_sf() +
  geom_sf(data = states, lwd = 1)+
  scale_fill_viridis_c()+
  geom_sf(data = fill_, aes(fill = percentPositive), color = gray(.5)) +
  coord_sf(xlim = c(-105.5, -79), ylim = c(36.15, 49.5), expand = FALSE) +
  labs(x="Latitude", y="Longitude", title="Midwest counties map") +
  theme(plot.title = element_text(hjust = 0.5))+
  theme_void()
library("plotly")
ggplotly(whole_map) %>% 
  add_trace(
    
  )

library(plotly)
fig <- plot_ly() 
fig <- fig %>%
  add_trace(
    type = "pie",
    name = "",
    values = c(2, 1, 3, 2.5),
    labels = c("R", "Python", "Java Script", "Matlab"),
    text = c("textA", "TextB", "TextC", "TextD"),
    hovertemplate = "%{label}: <br>Popularity: %{percent} </br> %{text}")


fig

```
I tried to setup the transmission rate and be able to zoom in by radio button, but my computer was giving me this error of server must be a function. 
```{r}
library("shiny")
wrangler<-function(df, statein){
  if(statein!="Whole"){
  df %>% 
    filter(state%in%statein)
  }
  else{
    df
  }
}
plot<-function(df){
  df %>% 
  group_by(county,state) %>% 
  summarise(percentPositive = mean(positive_pct)) %>% 
  mutate(ID = paste0(tolower(state),",",tolower(county))) %>% 
  ungroup() %>% 
  separate(ID, c("ID","county"), sep = " ") %>% 
  transmute(percentPositive,ID) %>% 
  right_join(counties) %>% 
  ggplot(data = world) +
  geom_sf() +
  geom_sf(lwd = 1)+
  scale_fill_viridis_c()+
  geom_sf(data = fill_, aes(fill = percentPositive), color = gray(.5)) +
  coord_sf(xlim = c(-105.5, -79), ylim = c(36.15, 49.5), expand = FALSE) +
  labs(x="Latitude", y="Longitude", title="Midwest counties map") +
  theme(plot.title = element_text(hjust = 0.5))+
  theme_void()
  
}
ui<-fluidPage(
  radioButtons("state","Choose which State to observe",choices = c("Whole",unique(vac_trans$state))),
  textOutput("text")
)
server<-function(input,output){
  covid_subset<-reactive({wrangler(vac_trans,input$state)})
  output$text<-renderText(paste("This is the radio button,", input$state))
}
runApp(ui,server)
```

```{r}
#I'd like to remove the annoying column labels on the bottom since it's kindof an eye sore.
library(superheat)
vac_trans %>% 
  group_by(state,date) %>% 
  summarise(trans_by_state=mean(positive_pct)) %>% 
  filter(!state%in%c("Iowa","Missouri")) %>% 
  pivot_wider(names_from = date, values_from = trans_by_state,values_fill=0) %>% 
  column_to_rownames(var = "state") %>% 
  superheat()
```
```{r}
#Kindof lame, but it helps to build an intuition of the dataset.
vac_trans$dose_1_pct[is.na(vac_trans$dose_1_pct)]=0
vac_trans %>% 
  group_by(date,state) %>% 
  summarise(first=mean(dose_1_pct), full = mean(fully_pct)) %>% 
  ggplot()+
  geom_line(aes(date,first,col=state,group=state))+
  geom_line(aes(date,full,col=state,group=state),linetype="dashed")+
  facet_wrap(~state)
#I think this graph could be helpful, but conversely it says that getting just one dose has a stronger negative linear correlation with being positive than two doses.
library("GGally")
vac_trans %>% 
  group_by(date,state) %>% 
  summarise(positve=mean(positive_pct), one=mean(dose_1_pct),full = mean(fully_pct)) %>% 
  ggpairs(columns = 3:5,method = c("everything","pearson"),aes(label=state)) 
```

